import { Metadata } from 'next';
import { ReactNode } from 'react';
import '../styles/style.scss';
import Providers from './providers';

export const metadata: Metadata = {
	description: 'Generated by create next app',
	title: 'Create Next App',
};

export default function RootLayout({ children }: Readonly<{ children: ReactNode }>) {
	return (
		<html lang="en">
			<body>
				<Providers>
					<main>{children}</main>
				</Providers>
			</body>
		</html>
	);
}
